# SPDX-License-Identifier: BUSL-1.1

development: true
logger:
  encoder: console
  level: debug
cmd/eskimo:
  host: localhost
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 443
    certPath: cmd/eskimo/.testdata/localhost.crt
    keyPath: cmd/eskimo/.testdata/localhost.key
cmd/eskimo-hut:
  host: localhost:1443
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 1443
    certPath: cmd/eskimo-hut/.testdata/localhost.crt
    keyPath: cmd/eskimo-hut/.testdata/localhost.key
users:
  db:
    spaces:
      - USERS
      - PHONE_NUMBER_VALIDATIONS
      - DAYS
      - USERS_PER_COUNTRY
      - DEVICE_SETTINGS
      - DEVICE_METADATA
    urls:
      - localhost:3301
    user: admin
    password: pass
  messageBroker:
    consumerGroup: eskimo-users-testing
    createTopics: true
    urls:
      - localhost:9092
    topics:
      - name: users-events
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: user-device-metadata-events
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: user-device-settings-events
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: mining-started-events
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: eskimo-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - users-events
      - mining-started-events
  ip2LocationBinaryPath: ./users/internal/device/metadata/.testdata/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE-SAMPLE.BIN
  pictureStorage:
    urlUpload: https://storage.bunnycdn.com/ice-staging/profile
    urlDownload: https://ice-staging.b-cdn.net/profile
    accessKey: access_key_hidden
  phoneNumberValidation:
    twilioCredentials:
      user: user_hidden
      password: password_hidden
    fromPhoneNumber: +12345678
    expirationTime: 3m
    smsTemplate: '{{.code}} is your ice verification code. This code expires in {{.expirationTime}} minutes.'
